module SCTP
  module Constants
    SCTP_RTOINFO = 0
    SCTP_ASSOCINFO = 1
    SCTP_INITMSG = 2
    SCTP_NODELAY = 3
    SCTP_AUTOCLOSE = 4
    SCTP_SET_PEER_PRIMARY_ADDR = 5
    SCTP_PRIMARY_ADDR = 6
    SCTP_ADAPTATION_LAYER = 7
    SCTP_DISABLE_FRAGMENTS = 8
    SCTP_PEER_ADDR_PARAMS = 9
    SCTP_DEFAULT_SEND_PARAM = 10
    SCTP_EVENTS = 11
    SCTP_I_WANT_MAPPED_V4_ADDR = 12
    SCTP_MAXSEG = 13
    SCTP_STATUS = 14
    SCTP_GET_PEER_ADDR_INFO = 15
    SCTP_DELAYED_ACK_TIME = 16
    SCTP_CONTEXT = 17
    SCTP_FRAGMENT_INTERLEAVE = 18
    SCTP_PARTIAL_DELIVERY_POINT = 19
    SCTP_MAX_BURST = 20
    SCTP_AUTH_CHUNK = 21
    SCTP_HMAC_IDENT = 22
    SCTP_AUTH_KEY = 23
    SCTP_AUTH_ACTIVE_KEY = 24
    SCTP_AUTH_DELETE_KEY = 25
    SCTP_PEER_AUTH_CHUNKS = 26
    SCTP_LOCAL_AUTH_CHUNKS = 27
    SCTP_GET_ASSOC_NUMBER = 28
    SCTP_SOCKOPT_BINDX_ADD = 100
    SCTP_SOCKOPT_BINDX_REM = 101
    SCTP_SOCKOPT_PEELOFF = 102
    SCTP_SOCKOPT_CONNECTX_OLD = 107
    SCTP_GET_PEER_ADDRS = 108
    SCTP_GET_LOCAL_ADDRS = 109
    SCTP_SOCKOPT_CONNECTX = 110
    SCTP_SOCKOPT_CONNECTX3 = 111
    SCTP_GET_ASSOC_STATS = 112
  end
end
