name: Ruby

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3
        bundler-cache: true
    - name: Install SCTP headers
      uses: actions/checkout@v4
      run: |
          sudo apt-get install libsctp-dev lksctp-tools
          sudo ip link add dummy1 type dummy
          sudo ip link add dummy2 type dummy
          sudo ip addr add 1.1.1.1/24 dev dummy1
          sudo ip addr add 1.1.1.2/24 dev dummy2
          sudo ip link set dummy1 up
          sudo ip link set dummy2 up
    - name: Run specs
      uses: ruby/setup-ruby@v1
      run: |
          gem install bundler --no-document
          bundle install --quiet
          bundle exec rake
