name: Ruby

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  test:
    steps:
    - name: Install Ruby and SCTP headers       
      uses: actions/checkout@v4
      with:
        usesh: true
        prepare: |
          apt-get install libsctp-dev lksctp-tools ruby
          ip link add dummy1 type dummy
          ip link add dummy2 type dummy
          ip addr add 1.1.1.1/24 dev dummy1
          ip addr add 1.1.1.2/24 dev dummy2
          ip link set dummy1 up
          ip link set dummy2 up
    - name: Run specs
      run: |
          gem install bundler --no-document
          bundle install --quiet
          bundle exec rake
