name: Ruby

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.2', '3.3', '3.4']
    steps:
    - uses: actions/checkout@v4
    - name: Install SCTP headers
      run: |
          sudo apt-get install libsctp-dev lksctp-tools
          sudo ip link add dummy1 type dummy
          sudo ip link add dummy2 type dummy
          sudo ip addr add 1.1.1.1/24 dev dummy1
          sudo ip addr add 1.1.1.2/24 dev dummy2
          sudo ip link set dummy1 up
          sudo ip link set dummy2 up
          sudo sysctl -w net.sctp.auth_enable=1
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Run Specs
      run: bundle exec rake
  freebsd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        prepare: |
          pkg install -y llvm ruby devel/ruby-gems sctplib git-tiny

        run: |
          git config --global --add safe.directory /home/runner/work/sctp-socket/sctp-socket
          kldload sctp
          ifconfig lo1 create
          ifconfig lo1 1.1.1.1/24 up
          ifconfig lo2 create
          ifconfig lo2 1.1.1.2/24 up
          gem install bundler --no-document
          bundle install --quiet
          bundle exec rake
